### PR TITLE
Fixes for hanging issue

### PR DESCRIPTION
**Pull request by pawelglosz**
Hello @brendanmorrell ,
I've fixed 2 bugs with my current changes:
- removed cloneDeep(), it looks like that at the end it wasn't needed at all
- fixed support for ChainExpressions as a jsx attributes (there was an error The prop value with an expression type of ChainExpression could not be resolved for such cases)

### CODE REVIEW

**Comment by pawelglosz** [comment]
Also, I've checked the functionality and performance on my few projects, everywhere it seems to work fine.

**Comment by brendanmorrell** [comment]
Awesome. Thanks, Pawel, and my apologies for not getting back to you about
the issues. I read the email while I was busy, and I forgot about it until
now. I'll try and take a look asap and then we can cut a release. Thanks
again!

**Comment by pawelglosz** [comment]
Please be aware, that there might be some breaking changes for some environments because of a major version update of jsx-ast-utils - it was needed for the ChainingExpression issue, please see the thread here: https://github.com/facebook/react/issues/19940#issuecomment-750933667

**Comment by brendanmorrell** [comment]
Noted. Thanks, Pawel

**Comment by pawelglosz** [comment]
Hello @brendanmorrell , any updates around this? :)

**Comment by brendanmorrell** [comment]
hey, pawel. very sorry.  have been super busy. thank you for fixing the
issue. i will do my best to test and get a new version out tonight

**Comment by brendanmorrell** [comment]
So, everything looking good when i run the project locally. Only thing I notice is that the code you added only fires an error if the styled component is defined inside of the object where you are placing it. if it is defined outside of the object, the rule no longer fires. I don't use this pattern personally, so not sure how much of an issue that is. If it isn't an accepted version of this pattern and you don't think an update is necessary, I'm good merg
Screen Shot 2022-07-28 at 11 03 49 AM
ing this and releasing a new version.

**Comment by pawelglosz** [comment]
It won't be an issue, I think we can release it as it is. I'll look at the case with a styled component defined outside of the object and try to add support for it as well. But this can be done in another release.

**Comment by brendanmorrell** [comment]
merged. new version with this change is `1.0.0`

**Comment by pawelglosz** [comment]
Thank you! I'll try to look into the case with a styled component defined outside of the object as soon as possible :)

**Pull request merged**
