### PR TITLE
Add support for styled components defined as objects

### PR DESCRIPTION
**Pull request by pawelglosz**

### CODE REVIEW

**Comment by brendanmorrell** [comment]
Thanks, Pawel! I'll run through it more thoroughly in a day or two, but looks great. Appreciate it!

**Comment by pawelglosz** [comment]
> Thanks, Pawel! I'll run through it more thoroughly in a day or two, but looks great. Appreciate it!

Thanks! Looking forward to hearing from you :)

**Comment by pawelglosz** [comment]
Hello @brendanmorrell ! How is it going? Did you manage to run through the changes?

**Comment by brendanmorrell** [comment]
I'm seeing a test error after merging. will try and take a look soon, but if you have time to take a look, I might be able to publish the new version more quickly.

**Comment by brendanmorrell** [comment]
@pawelglosz scratch that. Ran the tests again and they are passing. I was updating some things in my terminal while the tests were running, so maybe that caused a false positive. everything seems fine. Adding a note in the changelog and then publishing.

**Comment by brendanmorrell** [comment]
@pawelglosz having an. issue with my npm account. Should be resolved in a day or two. I'll ping you when your change is published. Thanks again!

**Comment by pawelglosz** [comment]
Nice, thank you!

**Comment by brendanmorrell** [comment]
@pawelglosz Got access to my account again and just published the package. Your changes are in version ```0.0.37```. Thanks for contributing!

**Comment by brendanmorrell** [comment]
@pawelglosz So, got a report of the new build hanging for someone (claim is that there is a memory leak introduced in this PR). While investigating that, I just thought I'd try the example you added to the readme 
```
const S = { Div: styled.div`` };
<S.Div onClick={() => null} />;
```
I am not getting the linter error for this in the most recent version. Are you? I remember all the tests pass, so I would expect it to work, but this code in my editor is not giving me any linter errors.

**Comment by brendanmorrell** [comment]
@pawelglosz It also unfortunately does appear that there was an issue with the PR. Running eslint from the command line on any of my projects with the most recent version would cause the terminal to hang, e.g., ```npx eslint ./```. Reverting this PR fixes the issue. I suspect that cloneDeep is probably what's causing the issue, but I will not have time to investigate more for a little bit. If you figure out what is going on, I'd love a follow-up PR. Thanks

**Comment by pawelglosz** [comment]
Thank you for the information, I'll look at the issue and try to fix it.

**Comment by pawelglosz** [comment]
And apologies for the issue!

**Pull request merged**
